/*

Copyright (c) 2010 - 2023, Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#ifndef NRF7140_BBPR_PERIPHERALS_H
#define NRF7140_BBPR_PERIPHERALS_H

#ifdef __cplusplus
    extern "C" {
#endif

#include <stdbool.h>
/*VPR CSR registers*/
#define VPRCSR_PRESENT
#define VPRCSR_COUNT 1

#define VPRCSR_HARTNUM 11
#define VPRCSR_MCLICBASERESET 4026531840
#define VPRCSR_MULDIV 1
#define VPRCSR_HIBERNATE 1
#define VPRCSR_DBG 1
#define VPRCSR_REMAP 0
#define VPRCSR_BUSWIDTH 64
#define VPRCSR_BKPT 1
#define VPRCSR_VIOPINS 8
#define VPRCSR_RT_SPLIT_SEC 0
#define VPRCSR_RT_SHIFT_PRESENT 0
#define VPRCSR_RT_SHIFT_START 0
#define VPRCSR_RT_SHIFT_LENGTH 32
#define VPRCSR_VEVIF_NTASKS_MIN 0
#define VPRCSR_VEVIF_NTASKS_MAX 15
#define VPRCSR_VEVIF_TASKS_MASK 65280
#define VPRCSR_VEVIF_NDPPI_MIN 8
#define VPRCSR_VEVIF_NDPPI_MAX 10
#define VPRCSR_VEVIF_NEVENTS_MIN 12
#define VPRCSR_VEVIF_NEVENTS_MAX 15
#define VPRCSR_RST_UNRECOV 0
#define VPRCSR_BEXT 0
#define VPRCSR_CACHE_EN false
#define VPRCSR_OUTMODE_VPR1_2 true

/*VPR CLIC registers*/
#define CLIC_PRESENT
#define CLIC_COUNT 1

#define VPRCLIC_IRQNUM_MIN 0
#define VPRCLIC_IRQNUM_MAX 479
#define VPRCLIC_CLIC_NTASKS_MIN 0
#define VPRCLIC_CLIC_NTASKS_MAX 15
#define VPRCLIC_CLIC_TASKS_MASK 65280
#define VPRCLIC_COUNTER_IRQ_NUM 16
#define VPRCLIC_CLIC_VPR_1_2 true

/*VTIM CSR registers*/
#define VTIM_PRESENT
#define VTIM_COUNT 1

/*Factory Information Configuration Registers*/
#define FICR_PRESENT
#define FICR_COUNT 1

#define FICR_LTE_ON false
#define FICR_WIFI_ON true
#define FICR_NFC_ON true

/*USBHSCORE*/
#define USBHSCORE_PRESENT
#define USBHSCORE_COUNT 1

/*I3CCORE*/
#define I3CCORE_PRESENT
#define I3CCORE_COUNT 2

/*MCAN*/
#define MCAN_PRESENT
#define MCAN_COUNT 2

/*DMU*/
#define DMU_PRESENT
#define DMU_COUNT 2

/*System Trace Macrocell data buffer*/
#define STMDATA_PRESENT
#define STMDATA_COUNT 1

/*TDDCONF*/
#define TDDCONF_PRESENT
#define TDDCONF_COUNT 1

#define TDDCONF_FEATEN_TDDCONF_CLK_320MHZ true
#define TDDCONF_FEATEN_TDDCONF_CLK_400MHZ false

/*GENERIC*/
#define GENERIC_PRESENT
#define GENERIC_COUNT 3

/*System Trace Macrocell*/
#define STM_PRESENT
#define STM_COUNT 1

/*Trace Port Interface Unit*/
#define TPIU_PRESENT
#define TPIU_COUNT 1

/*Cross-Trigger Interface control*/
#define CTI_PRESENT
#define CTI_COUNT 2

/*ATB Replicator module*/
#define ATBREPLICATOR_PRESENT
#define ATBREPLICATOR_COUNT 4

/*ATB funnel module*/
#define ATBFUNNEL_PRESENT
#define ATBFUNNEL_COUNT 4

/*AUXPLL*/
#define AUXPLL_PRESENT
#define AUXPLL_COUNT 2

/*HSFLL*/
#define HSFLL_PRESENT
#define HSFLL_COUNT 1

#define HSFLL300_DITHER_32B true

/*LRCCONF*/
#define LRCCONF_PRESENT
#define LRCCONF_COUNT 2

#define LRCCONF300_POWERON true
#define LRCCONF300_RETAIN true
#define LRCCONF300_SYSTEMOFF true
#define LRCCONF300_LRCREQHFXO true
#define LRCCONF300_NCLK_MIN 0
#define LRCCONF300_NCLK_MAX 7
#define LRCCONF300_CLKCTRL false
#define LRCCONF300_NACTPD_MIN 0
#define LRCCONF300_NACTPD_MAX 0
#define LRCCONF300_PDACT true
#define LRCCONF300_NPD_MIN 0
#define LRCCONF300_NPD_MAX 7
#define LRCCONF300_OTHERON false
#define LRCCONF300_NDOMAINS_MIN 0
#define LRCCONF300_NDOMAINS_MAX 15
#define LRCCONF300_AX2XWAITSTATES false
#define LRCCONF300_POWERON_MAIN_RESET 0
#define LRCCONF300_POWERON_ACT_RESET 0
#define LRCCONF300_RETAIN_MAIN_RESET 1
#define LRCCONF300_RETAIN_ACT_RESET 1

#define LRCCONF310_POWERON true
#define LRCCONF310_RETAIN true
#define LRCCONF310_SYSTEMOFF true
#define LRCCONF310_LRCREQHFXO true
#define LRCCONF310_NCLK_MIN 0
#define LRCCONF310_NCLK_MAX 7
#define LRCCONF310_CLKCTRL false
#define LRCCONF310_NACTPD_MIN 0
#define LRCCONF310_NACTPD_MAX 0
#define LRCCONF310_PDACT true
#define LRCCONF310_NPD_MIN 0
#define LRCCONF310_NPD_MAX 7
#define LRCCONF310_OTHERON false
#define LRCCONF310_NDOMAINS_MIN 0
#define LRCCONF310_NDOMAINS_MAX 15
#define LRCCONF310_AX2XWAITSTATES false
#define LRCCONF310_POWERON_MAIN_RESET 0
#define LRCCONF310_POWERON_ACT_RESET 0
#define LRCCONF310_RETAIN_MAIN_RESET 1
#define LRCCONF310_RETAIN_ACT_RESET 1

/*PCGC Master*/
#define PCGCMASTER_PRESENT
#define PCGCMASTER_COUNT 2

#define PCGCM300_POWERCONSUMPTIONCALC true
#define PCGCM300_SETPWRCONTHRESHOLDBASE true
#define PCGCM300_CLOCKFORCEREG true
#define PCGCM300_MASTERFORCEREG true

#define PCGCM310_POWERCONSUMPTIONCALC true
#define PCGCM310_SETPWRCONTHRESHOLDBASE true
#define PCGCM310_CLOCKFORCEREG true
#define PCGCM310_MASTERFORCEREG true

/*Memory configuration*/
#define MEMCONF_PRESENT
#define MEMCONF_COUNT 1

#define MEMCONF310_RETTRIM true
#define MEMCONF310_REPAIR false
#define MEMCONF310_POWER true
#define MEMCONF310_RET2 true

/*PCGCSlave*/
#define PCGCSLAVE_PRESENT
#define PCGCSLAVE_COUNT 1

#define PCGCS310_PENALTYTASKS false

/*GPIO Tasks and Events*/
#define GPIOTE_PRESENT
#define GPIOTE_COUNT 1

#define GPIOTE130_GPIOTE_NCHANNELS_MIN 0
#define GPIOTE130_GPIOTE_NCHANNELS_MAX 7
#define GPIOTE130_GPIOTE_NPORTEVENTS_MIN 0
#define GPIOTE130_GPIOTE_NPORTEVENTS_MAX 3
#define GPIOTE130_GPIOTE_NINTERRUPTS_MIN 0
#define GPIOTE130_GPIOTE_NINTERRUPTS_MAX 1

/*Global Real-time counter*/
#define GRTC_PRESENT
#define GRTC_COUNT 1

#define GRTC_MSBWIDTH_MIN 0
#define GRTC_MSBWIDTH_MAX 14
#define GRTC_NCC_MIN 0
#define GRTC_NCC_MAX 23
#define GRTC_NTIMEOUT_MIN 0
#define GRTC_NTIMEOUT_MAX 15
#define GRTC_NDOMAIN_MIN 0
#define GRTC_NDOMAIN_MAX 15
#define GRTC_GRTC_NINTERRUPTS_MIN 0
#define GRTC_GRTC_NINTERRUPTS_MAX 2
#define GRTC_PWMREGS true
#define GRTC_CLKOUTREG true
#define GRTC_CLKSELREG false

/*GSI*/
#define GSI_PRESENT
#define GSI_COUNT 1

/*DISPC*/
#define DISPC_PRESENT
#define DISPC_COUNT 1

/*GPU*/
#define GPU_PRESENT
#define GPU_COUNT 1

/*Trace buffer monitor*/
#define TBM_PRESENT
#define TBM_COUNT 1

/*USBHS*/
#define USBHS_PRESENT
#define USBHS_COUNT 1

/*MRAM controller*/
#define MRAMC_PRESENT
#define MRAMC_COUNT 2

#define MRAMC110_NMRAMWORDSIZE 128
#define MRAMC110_NMRAMPAGESIZE 4
#define MRAMC110_NNVRPAGESIZE 4
#define MRAMC110_NMAINMEMORYSIZE 2
#define MRAMC110_NNVRPAGES_MIN 0
#define MRAMC110_NNVRPAGES_MAX 3
#define MRAMC110_NSIZEMRAMWORDS_MIN 1
#define MRAMC110_NSIZEMRAMWORDS_MAX 131072
#define MRAMC110_MARMDATAWIDTHWORDS_MIN 0
#define MRAMC110_MARMDATAWIDTHWORDS_MAX 3
#define MRAMC110_NVRPAGEUPPER true
#define MRAMC110_NVRPAGELOWER true
#define MRAMC110_NVRPAGEENABLENORMALWRITE true
#define MRAMC110_NVRPAGELRSIZEBITS_MIN 24
#define MRAMC110_NVRPAGELRSIZEBITS_MAX 27
#define MRAMC110_NVRPAGELRSIZERESET 15
#define MRAMC110_NVRPAGELRSIZEVALUE_MIN 0
#define MRAMC110_NVRPAGELRSIZEVALUE_MAX 15
#define MRAMC110_NVRPAGELWSIZEBITS_MIN 28
#define MRAMC110_NVRPAGELWSIZEBITS_MAX 31
#define MRAMC110_NVRPAGELWSIZERESET 15
#define MRAMC110_NVRPAGELWSIZEVALUE_MIN 0
#define MRAMC110_NVRPAGELWSIZEVALUE_MAX 15

#define MRAMC111_NMRAMWORDSIZE 128
#define MRAMC111_NMRAMPAGESIZE 4
#define MRAMC111_NNVRPAGESIZE 4
#define MRAMC111_NMAINMEMORYSIZE 2
#define MRAMC111_NNVRPAGES_MIN 0
#define MRAMC111_NNVRPAGES_MAX 3
#define MRAMC111_NSIZEMRAMWORDS_MIN 1
#define MRAMC111_NSIZEMRAMWORDS_MAX 131072
#define MRAMC111_MARMDATAWIDTHWORDS_MIN 0
#define MRAMC111_MARMDATAWIDTHWORDS_MAX 3
#define MRAMC111_NVRPAGEUPPER false
#define MRAMC111_NVRPAGELOWER false
#define MRAMC111_NVRPAGEENABLENORMALWRITE true
#define MRAMC111_NVRPAGELRSIZEBITS_MIN 24
#define MRAMC111_NVRPAGELRSIZEBITS_MAX 27
#define MRAMC111_NVRPAGELRSIZERESET 15
#define MRAMC111_NVRPAGELRSIZEVALUE_MIN 0
#define MRAMC111_NVRPAGELRSIZEVALUE_MAX 15
#define MRAMC111_NVRPAGELWSIZEBITS_MIN 28
#define MRAMC111_NVRPAGELWSIZEBITS_MAX 31
#define MRAMC111_NVRPAGELWSIZERESET 15
#define MRAMC111_NVRPAGELWSIZEVALUE_MIN 0
#define MRAMC111_NVRPAGELWSIZEVALUE_MAX 15

/*External Memory Interface*/
#define EXMIF_PRESENT
#define EXMIF_COUNT 1

/*AUXPM*/
#define AUXPM_PRESENT
#define AUXPM_COUNT 1

/*OTP controller*/
#define OTPC_PRESENT
#define OTPC_COUNT 1

#define OTPC_REGION_NO_EXTENSION false
#define OTPC_REGION_EXTENSION true
#define OTPC_NREGIONS_MIN 0
#define OTPC_NREGIONS_MAX 5
#define OTPC_REGION0ADDR 797179904
#define OTPC_REGION0SIZE 768
#define OTPC_REGION1ADDR 797180672
#define OTPC_REGION1SIZE 256
#define OTPC_REGION2ADDR 797180928
#define OTPC_REGION2SIZE 768
#define OTPC_REGION3ADDR 797181696
#define OTPC_REGION3SIZE 768
#define OTPC_REGION4ADDR 797182464
#define OTPC_REGION4SIZE 512
#define OTPC_REGION5ADDR 797182976
#define OTPC_REGION5SIZE 13312

/*VPR peripheral registers*/
#define VPR_PRESENT
#define VPR_COUNT 3

#define VPR120_INIT_PC_RESET_VALUE 796917760
#define VPR120_VPR_START_RESET_VALUE 1
#define VPR120_RAM_BASE_ADDR 797442048
#define VPR120_RAM_SZ 16
#define VPR120_VPRSAVEDCTX_REGNAME NRF_MEMCONF120->POWER[0].RET
#define VPR120_VPRSAVEDCTX_REGBIT 22
#define VPR120_RETAINED 0
#define VPR120_VPRSAVEDCTX true
#define VPR120_VPRSAVEADDR 797442048
#define VPR120_VPRREMAPADDRVTOB 797179904
#define VPR120_VEVIF_NTASKS_MIN 0
#define VPR120_VEVIF_NTASKS_MAX 31
#define VPR120_VEVIF_TASKS_MASK 4294963455
#define VPR120_VEVIF_NDPPI_MIN 24
#define VPR120_VEVIF_NDPPI_MAX 27
#define VPR120_VEVIF_NEVENTS_MIN 28
#define VPR120_VEVIF_NEVENTS_MAX 31
#define VPR120_DEBUGGER_OFFSET 1024

#define VPR121_INIT_PC_RESET_VALUE 0
#define VPR121_VPR_START_RESET_VALUE 0
#define VPR121_RAM_BASE_ADDR 797507584
#define VPR121_RAM_SZ 15
#define VPR121_VPRSAVEDCTX_REGNAME NRF_MEMCONF120->POWER[0].RET
#define VPR121_VPRSAVEDCTX_REGBIT 23
#define VPR121_RETAINED 0
#define VPR121_VPRSAVEDCTX true
#define VPR121_VPRSAVEADDR 796917760
#define VPR121_VPRREMAPADDRVTOB 0
#define VPR121_VEVIF_NTASKS_MIN 0
#define VPR121_VEVIF_NTASKS_MAX 31
#define VPR121_VEVIF_TASKS_MASK 4294901760
#define VPR121_VEVIF_NDPPI_MIN 24
#define VPR121_VEVIF_NDPPI_MAX 27
#define VPR121_VEVIF_NEVENTS_MIN 28
#define VPR121_VEVIF_NEVENTS_MAX 31
#define VPR121_DEBUGGER_OFFSET 1024

#define VPR130_INIT_PC_RESET_VALUE 0
#define VPR130_VPR_START_RESET_VALUE 0
#define VPR130_RAM_BASE_ADDR 801112064
#define VPR130_RAM_SZ 15
#define VPR130_VPRSAVEDCTX_REGNAME NRF_MEMCONF130->POWER[0].RET
#define VPR130_VPRSAVEDCTX_REGBIT 5
#define VPR130_RETAINED 1
#define VPR130_VPRSAVEDCTX true
#define VPR130_VPRSAVEADDR 796917760
#define VPR130_VPRREMAPADDRVTOB 0
#define VPR130_VEVIF_NTASKS_MIN 0
#define VPR130_VEVIF_NTASKS_MAX 15
#define VPR130_VEVIF_TASKS_MASK 65520
#define VPR130_VEVIF_NDPPI_MIN 8
#define VPR130_VEVIF_NDPPI_MAX 11
#define VPR130_VEVIF_NEVENTS_MIN 12
#define VPR130_VEVIF_NEVENTS_MAX 15
#define VPR130_DEBUGGER_OFFSET 1024

/*IPCT APB registers*/
#define IPCT_PRESENT
#define IPCT_COUNT 2

/*MUTEX*/
#define MUTEX_PRESENT
#define MUTEX_COUNT 2

/*Prototype HW information registers.*/
#define PROTOTYPEINFO_PRESENT
#define PROTOTYPEINFO_COUNT 1

/*I3C*/
#define I3C_PRESENT
#define I3C_COUNT 2

/*Serial Peripheral Interface Master with EasyDMA*/
#define SPIM_PRESENT
#define SPIM_COUNT 12

#define SPIM122_EASYDMA5 true
#define SPIM122_EASYDMATEMP false
#define SPIM122_EASYDMALISTINCLUDED true
#define SPIM122_EASYDMAMODEINCLUDED false
#define SPIM122_EASYDMAFULLLPMODEINCLUDED false
#define SPIM122_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM122_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM122_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM122_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM122_EASYDMASTOPTASKINCLUDED true
#define SPIM122_MAX_DATARATE 32
#define SPIM122_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM122_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM122_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM122_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM122_FEATURE_RXDELAY_PRESENT true
#define SPIM122_STALL_STATUS_PRESENT false
#define SPIM122_STALL_STATUS_TX_PRESENT false
#define SPIM122_HSSPI false
#define SPIM122_HIGH_SPEED_DOMAIN true
#define SPIM122_MULTIPLE_CHIPSELECT true
#define SPIM122_NUM_CHIPSELECT_MIN 0
#define SPIM122_NUM_CHIPSELECT_MAX 0
#define SPIM122_CORE_FREQUENCY 320
#define SPIM122_PRESCALER_PRESENT true
#define SPIM122_PRESCALER_DIVISOR_RANGE_MIN 4
#define SPIM122_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM123_EASYDMA5 true
#define SPIM123_EASYDMATEMP false
#define SPIM123_EASYDMALISTINCLUDED true
#define SPIM123_EASYDMAMODEINCLUDED false
#define SPIM123_EASYDMAFULLLPMODEINCLUDED false
#define SPIM123_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM123_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM123_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM123_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM123_EASYDMASTOPTASKINCLUDED true
#define SPIM123_MAX_DATARATE 32
#define SPIM123_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM123_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM123_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM123_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM123_FEATURE_RXDELAY_PRESENT true
#define SPIM123_STALL_STATUS_PRESENT false
#define SPIM123_STALL_STATUS_TX_PRESENT false
#define SPIM123_HSSPI false
#define SPIM123_HIGH_SPEED_DOMAIN true
#define SPIM123_MULTIPLE_CHIPSELECT true
#define SPIM123_NUM_CHIPSELECT_MIN 0
#define SPIM123_NUM_CHIPSELECT_MAX 0
#define SPIM123_CORE_FREQUENCY 320
#define SPIM123_PRESCALER_PRESENT true
#define SPIM123_PRESCALER_DIVISOR_RANGE_MIN 4
#define SPIM123_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM120_EASYDMA5 true
#define SPIM120_EASYDMATEMP false
#define SPIM120_EASYDMALISTINCLUDED true
#define SPIM120_EASYDMAMODEINCLUDED false
#define SPIM120_EASYDMAFULLLPMODEINCLUDED false
#define SPIM120_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM120_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM120_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM120_EASYDMASTOPTASKINCLUDED true
#define SPIM120_MAX_DATARATE 32
#define SPIM120_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM120_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM120_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM120_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM120_FEATURE_RXDELAY_PRESENT true
#define SPIM120_STALL_STATUS_PRESENT false
#define SPIM120_STALL_STATUS_TX_PRESENT false
#define SPIM120_HSSPI false
#define SPIM120_HIGH_SPEED_DOMAIN true
#define SPIM120_MULTIPLE_CHIPSELECT true
#define SPIM120_NUM_CHIPSELECT_MIN 0
#define SPIM120_NUM_CHIPSELECT_MAX 0
#define SPIM120_CORE_FREQUENCY 320
#define SPIM120_PRESCALER_PRESENT true
#define SPIM120_PRESCALER_DIVISOR_RANGE_MIN 4
#define SPIM120_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM121_EASYDMA5 true
#define SPIM121_EASYDMATEMP false
#define SPIM121_EASYDMALISTINCLUDED true
#define SPIM121_EASYDMAMODEINCLUDED false
#define SPIM121_EASYDMAFULLLPMODEINCLUDED false
#define SPIM121_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM121_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM121_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM121_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM121_EASYDMASTOPTASKINCLUDED true
#define SPIM121_MAX_DATARATE 32
#define SPIM121_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM121_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM121_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM121_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM121_FEATURE_RXDELAY_PRESENT true
#define SPIM121_STALL_STATUS_PRESENT false
#define SPIM121_STALL_STATUS_TX_PRESENT false
#define SPIM121_HSSPI false
#define SPIM121_HIGH_SPEED_DOMAIN true
#define SPIM121_MULTIPLE_CHIPSELECT true
#define SPIM121_NUM_CHIPSELECT_MIN 0
#define SPIM121_NUM_CHIPSELECT_MAX 0
#define SPIM121_CORE_FREQUENCY 320
#define SPIM121_PRESCALER_PRESENT true
#define SPIM121_PRESCALER_DIVISOR_RANGE_MIN 4
#define SPIM121_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM130_EASYDMA5 true
#define SPIM130_EASYDMATEMP false
#define SPIM130_EASYDMALISTINCLUDED true
#define SPIM130_EASYDMAMODEINCLUDED false
#define SPIM130_EASYDMAFULLLPMODEINCLUDED false
#define SPIM130_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM130_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM130_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM130_EASYDMASTOPTASKINCLUDED true
#define SPIM130_MAX_DATARATE 8
#define SPIM130_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM130_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM130_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM130_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM130_FEATURE_RXDELAY_PRESENT true
#define SPIM130_STALL_STATUS_PRESENT false
#define SPIM130_STALL_STATUS_TX_PRESENT false
#define SPIM130_HSSPI false
#define SPIM130_HIGH_SPEED_DOMAIN false
#define SPIM130_MULTIPLE_CHIPSELECT true
#define SPIM130_NUM_CHIPSELECT_MIN 0
#define SPIM130_NUM_CHIPSELECT_MAX 0
#define SPIM130_CORE_FREQUENCY 64
#define SPIM130_PRESCALER_PRESENT true
#define SPIM130_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM130_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM131_EASYDMA5 true
#define SPIM131_EASYDMATEMP false
#define SPIM131_EASYDMALISTINCLUDED true
#define SPIM131_EASYDMAMODEINCLUDED false
#define SPIM131_EASYDMAFULLLPMODEINCLUDED false
#define SPIM131_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM131_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM131_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM131_EASYDMASTOPTASKINCLUDED true
#define SPIM131_MAX_DATARATE 8
#define SPIM131_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM131_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM131_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM131_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM131_FEATURE_RXDELAY_PRESENT true
#define SPIM131_STALL_STATUS_PRESENT false
#define SPIM131_STALL_STATUS_TX_PRESENT false
#define SPIM131_HSSPI false
#define SPIM131_HIGH_SPEED_DOMAIN false
#define SPIM131_MULTIPLE_CHIPSELECT true
#define SPIM131_NUM_CHIPSELECT_MIN 0
#define SPIM131_NUM_CHIPSELECT_MAX 0
#define SPIM131_CORE_FREQUENCY 64
#define SPIM131_PRESCALER_PRESENT true
#define SPIM131_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM131_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM132_EASYDMA5 true
#define SPIM132_EASYDMATEMP false
#define SPIM132_EASYDMALISTINCLUDED true
#define SPIM132_EASYDMAMODEINCLUDED false
#define SPIM132_EASYDMAFULLLPMODEINCLUDED false
#define SPIM132_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM132_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM132_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM132_EASYDMASTOPTASKINCLUDED true
#define SPIM132_MAX_DATARATE 8
#define SPIM132_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM132_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM132_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM132_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM132_FEATURE_RXDELAY_PRESENT true
#define SPIM132_STALL_STATUS_PRESENT false
#define SPIM132_STALL_STATUS_TX_PRESENT false
#define SPIM132_HSSPI false
#define SPIM132_HIGH_SPEED_DOMAIN false
#define SPIM132_MULTIPLE_CHIPSELECT true
#define SPIM132_NUM_CHIPSELECT_MIN 0
#define SPIM132_NUM_CHIPSELECT_MAX 0
#define SPIM132_CORE_FREQUENCY 64
#define SPIM132_PRESCALER_PRESENT true
#define SPIM132_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM132_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM133_EASYDMA5 true
#define SPIM133_EASYDMATEMP false
#define SPIM133_EASYDMALISTINCLUDED true
#define SPIM133_EASYDMAMODEINCLUDED false
#define SPIM133_EASYDMAFULLLPMODEINCLUDED false
#define SPIM133_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM133_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM133_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM133_EASYDMASTOPTASKINCLUDED true
#define SPIM133_MAX_DATARATE 8
#define SPIM133_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM133_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM133_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM133_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM133_FEATURE_RXDELAY_PRESENT true
#define SPIM133_STALL_STATUS_PRESENT false
#define SPIM133_STALL_STATUS_TX_PRESENT false
#define SPIM133_HSSPI false
#define SPIM133_HIGH_SPEED_DOMAIN false
#define SPIM133_MULTIPLE_CHIPSELECT true
#define SPIM133_NUM_CHIPSELECT_MIN 0
#define SPIM133_NUM_CHIPSELECT_MAX 0
#define SPIM133_CORE_FREQUENCY 64
#define SPIM133_PRESCALER_PRESENT true
#define SPIM133_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM133_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM134_EASYDMA5 true
#define SPIM134_EASYDMATEMP false
#define SPIM134_EASYDMALISTINCLUDED true
#define SPIM134_EASYDMAMODEINCLUDED false
#define SPIM134_EASYDMAFULLLPMODEINCLUDED false
#define SPIM134_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM134_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM134_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM134_EASYDMASTOPTASKINCLUDED true
#define SPIM134_MAX_DATARATE 8
#define SPIM134_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM134_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM134_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM134_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM134_FEATURE_RXDELAY_PRESENT true
#define SPIM134_STALL_STATUS_PRESENT false
#define SPIM134_STALL_STATUS_TX_PRESENT false
#define SPIM134_HSSPI false
#define SPIM134_HIGH_SPEED_DOMAIN false
#define SPIM134_MULTIPLE_CHIPSELECT true
#define SPIM134_NUM_CHIPSELECT_MIN 0
#define SPIM134_NUM_CHIPSELECT_MAX 0
#define SPIM134_CORE_FREQUENCY 64
#define SPIM134_PRESCALER_PRESENT true
#define SPIM134_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM134_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM135_EASYDMA5 true
#define SPIM135_EASYDMATEMP false
#define SPIM135_EASYDMALISTINCLUDED true
#define SPIM135_EASYDMAMODEINCLUDED false
#define SPIM135_EASYDMAFULLLPMODEINCLUDED false
#define SPIM135_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM135_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM135_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM135_EASYDMASTOPTASKINCLUDED true
#define SPIM135_MAX_DATARATE 8
#define SPIM135_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM135_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM135_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM135_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM135_FEATURE_RXDELAY_PRESENT true
#define SPIM135_STALL_STATUS_PRESENT false
#define SPIM135_STALL_STATUS_TX_PRESENT false
#define SPIM135_HSSPI false
#define SPIM135_HIGH_SPEED_DOMAIN false
#define SPIM135_MULTIPLE_CHIPSELECT true
#define SPIM135_NUM_CHIPSELECT_MIN 0
#define SPIM135_NUM_CHIPSELECT_MAX 0
#define SPIM135_CORE_FREQUENCY 64
#define SPIM135_PRESCALER_PRESENT true
#define SPIM135_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM135_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM136_EASYDMA5 true
#define SPIM136_EASYDMATEMP false
#define SPIM136_EASYDMALISTINCLUDED true
#define SPIM136_EASYDMAMODEINCLUDED false
#define SPIM136_EASYDMAFULLLPMODEINCLUDED false
#define SPIM136_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM136_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM136_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM136_EASYDMASTOPTASKINCLUDED true
#define SPIM136_MAX_DATARATE 8
#define SPIM136_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM136_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM136_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM136_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM136_FEATURE_RXDELAY_PRESENT true
#define SPIM136_STALL_STATUS_PRESENT false
#define SPIM136_STALL_STATUS_TX_PRESENT false
#define SPIM136_HSSPI false
#define SPIM136_HIGH_SPEED_DOMAIN false
#define SPIM136_MULTIPLE_CHIPSELECT true
#define SPIM136_NUM_CHIPSELECT_MIN 0
#define SPIM136_NUM_CHIPSELECT_MAX 0
#define SPIM136_CORE_FREQUENCY 64
#define SPIM136_PRESCALER_PRESENT true
#define SPIM136_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM136_PRESCALER_DIVISOR_RANGE_MAX 126

#define SPIM137_EASYDMA5 true
#define SPIM137_EASYDMATEMP false
#define SPIM137_EASYDMALISTINCLUDED true
#define SPIM137_EASYDMAMODEINCLUDED false
#define SPIM137_EASYDMAFULLLPMODEINCLUDED false
#define SPIM137_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIM137_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIM137_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIM137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIM137_EASYDMASTOPTASKINCLUDED true
#define SPIM137_MAX_DATARATE 8
#define SPIM137_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIM137_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIM137_FEATURE_HARDWARE_CSN_PRESENT true
#define SPIM137_FEATURE_HARDWARE_DCX_PRESENT true
#define SPIM137_FEATURE_RXDELAY_PRESENT true
#define SPIM137_STALL_STATUS_PRESENT false
#define SPIM137_STALL_STATUS_TX_PRESENT false
#define SPIM137_HSSPI false
#define SPIM137_HIGH_SPEED_DOMAIN false
#define SPIM137_MULTIPLE_CHIPSELECT true
#define SPIM137_NUM_CHIPSELECT_MIN 0
#define SPIM137_NUM_CHIPSELECT_MAX 0
#define SPIM137_CORE_FREQUENCY 64
#define SPIM137_PRESCALER_PRESENT true
#define SPIM137_PRESCALER_DIVISOR_RANGE_MIN 2
#define SPIM137_PRESCALER_DIVISOR_RANGE_MAX 126

/*Quad serial peripheral interface*/
#define QSPI_PRESENT
#define QSPI_COUNT 2

/*Controller Area Network*/
#define CAN_PRESENT
#define CAN_COUNT 2

/*MVDMA performs direct-memory-accesses between memories. Data is transferred according to job descriptor lists. Each transfer has corresponding source and sink descriptor lists with matching data amounts. The lists are in memory and they contain data buffer information, address pointers, buffer sizes and data type attributes.*/
                                                                                                                                  
#define MVDMA_PRESENT
#define MVDMA_COUNT 2

#define MVDMA120_COMPLETED_EVENT true
#define MVDMA120_DPPI_DISCONNECTED true
#define MVDMA120_INSTANCE_IN_WRAPPER true

#define MVDMA121_COMPLETED_EVENT true
#define MVDMA121_DPPI_DISCONNECTED true
#define MVDMA121_INSTANCE_IN_WRAPPER true

/*RAM Controller*/
#define RAMC_PRESENT
#define RAMC_COUNT 2

#define RAMC122_ECC false
#define RAMC122_SEC false

#define RAMC123_ECC false
#define RAMC123_SEC false

/*Distributed programmable peripheral interconnect controller*/
#define DPPIC_PRESENT
#define DPPIC_COUNT 8

#define DPPIC120_HASCHANNELGROUPS true
#define DPPIC120_CH_NUM_MIN 0
#define DPPIC120_CH_NUM_MAX 7
#define DPPIC120_GROUP_NUM_MIN 0
#define DPPIC120_GROUP_NUM_MAX 1

#define DPPIC130_HASCHANNELGROUPS true
#define DPPIC130_CH_NUM_MIN 0
#define DPPIC130_CH_NUM_MAX 7
#define DPPIC130_GROUP_NUM_MIN 0
#define DPPIC130_GROUP_NUM_MAX 1

#define DPPIC131_HASCHANNELGROUPS true
#define DPPIC131_CH_NUM_MIN 0
#define DPPIC131_CH_NUM_MAX 7
#define DPPIC131_GROUP_NUM_MIN 0
#define DPPIC131_GROUP_NUM_MAX 1

#define DPPIC132_HASCHANNELGROUPS true
#define DPPIC132_CH_NUM_MIN 0
#define DPPIC132_CH_NUM_MAX 7
#define DPPIC132_GROUP_NUM_MIN 0
#define DPPIC132_GROUP_NUM_MAX 1

#define DPPIC133_HASCHANNELGROUPS true
#define DPPIC133_CH_NUM_MIN 0
#define DPPIC133_CH_NUM_MAX 7
#define DPPIC133_GROUP_NUM_MIN 0
#define DPPIC133_GROUP_NUM_MAX 1

#define DPPIC134_HASCHANNELGROUPS true
#define DPPIC134_CH_NUM_MIN 0
#define DPPIC134_CH_NUM_MAX 7
#define DPPIC134_GROUP_NUM_MIN 0
#define DPPIC134_GROUP_NUM_MAX 1

#define DPPIC135_HASCHANNELGROUPS true
#define DPPIC135_CH_NUM_MIN 0
#define DPPIC135_CH_NUM_MAX 7
#define DPPIC135_GROUP_NUM_MIN 0
#define DPPIC135_GROUP_NUM_MAX 1

#define DPPIC136_HASCHANNELGROUPS true
#define DPPIC136_CH_NUM_MIN 0
#define DPPIC136_CH_NUM_MAX 7
#define DPPIC136_GROUP_NUM_MIN 0
#define DPPIC136_GROUP_NUM_MAX 1

/*Timer/Counter*/
#define TIMER_PRESENT
#define TIMER_COUNT 10

#define TIMER120_CC_NUM_MIN 0
#define TIMER120_CC_NUM_MAX 5
#define TIMER120_MAX_SIZE_MIN 0
#define TIMER120_MAX_SIZE_MAX 31

#define TIMER121_CC_NUM_MIN 0
#define TIMER121_CC_NUM_MAX 5
#define TIMER121_MAX_SIZE_MIN 0
#define TIMER121_MAX_SIZE_MAX 31

#define TIMER130_CC_NUM_MIN 0
#define TIMER130_CC_NUM_MAX 5
#define TIMER130_MAX_SIZE_MIN 0
#define TIMER130_MAX_SIZE_MAX 31

#define TIMER131_CC_NUM_MIN 0
#define TIMER131_CC_NUM_MAX 5
#define TIMER131_MAX_SIZE_MIN 0
#define TIMER131_MAX_SIZE_MAX 31

#define TIMER132_CC_NUM_MIN 0
#define TIMER132_CC_NUM_MAX 5
#define TIMER132_MAX_SIZE_MIN 0
#define TIMER132_MAX_SIZE_MAX 31

#define TIMER133_CC_NUM_MIN 0
#define TIMER133_CC_NUM_MAX 5
#define TIMER133_MAX_SIZE_MIN 0
#define TIMER133_MAX_SIZE_MAX 31

#define TIMER134_CC_NUM_MIN 0
#define TIMER134_CC_NUM_MAX 5
#define TIMER134_MAX_SIZE_MIN 0
#define TIMER134_MAX_SIZE_MAX 31

#define TIMER135_CC_NUM_MIN 0
#define TIMER135_CC_NUM_MAX 5
#define TIMER135_MAX_SIZE_MIN 0
#define TIMER135_MAX_SIZE_MAX 31

#define TIMER136_CC_NUM_MIN 0
#define TIMER136_CC_NUM_MAX 5
#define TIMER136_MAX_SIZE_MIN 0
#define TIMER136_MAX_SIZE_MAX 31

#define TIMER137_CC_NUM_MIN 0
#define TIMER137_CC_NUM_MAX 5
#define TIMER137_MAX_SIZE_MIN 0
#define TIMER137_MAX_SIZE_MAX 31

/*Pulse width modulation unit*/
#define PWM_PRESENT
#define PWM_COUNT 5

#define PWM120_EASYDMA5 true
#define PWM120_EASYDMATEMP false
#define PWM120_IDLE_OUT true
#define PWM120_COMPARE_MATCH true
#define PWM120_FEATURES_V2 false
#define PWM120_NO_FEATURES_V2 true
#define PWM120_EASYDMALISTINCLUDED false
#define PWM120_EASYDMAMODEINCLUDED false
#define PWM120_EASYDMAFULLLPMODEINCLUDED false
#define PWM120_EASYDMAPATTERNMATCHERINCLUDED false
#define PWM120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED true
#define PWM120_EASYDMASTOPTASKINCLUDED true

#define PWM130_EASYDMA5 true
#define PWM130_EASYDMATEMP false
#define PWM130_IDLE_OUT true
#define PWM130_COMPARE_MATCH true
#define PWM130_FEATURES_V2 false
#define PWM130_NO_FEATURES_V2 true
#define PWM130_EASYDMALISTINCLUDED false
#define PWM130_EASYDMAMODEINCLUDED false
#define PWM130_EASYDMAFULLLPMODEINCLUDED false
#define PWM130_EASYDMAPATTERNMATCHERINCLUDED false
#define PWM130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED true
#define PWM130_EASYDMASTOPTASKINCLUDED true

#define PWM131_EASYDMA5 true
#define PWM131_EASYDMATEMP false
#define PWM131_IDLE_OUT true
#define PWM131_COMPARE_MATCH true
#define PWM131_FEATURES_V2 false
#define PWM131_NO_FEATURES_V2 true
#define PWM131_EASYDMALISTINCLUDED false
#define PWM131_EASYDMAMODEINCLUDED false
#define PWM131_EASYDMAFULLLPMODEINCLUDED false
#define PWM131_EASYDMAPATTERNMATCHERINCLUDED false
#define PWM131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED true
#define PWM131_EASYDMASTOPTASKINCLUDED true

#define PWM132_EASYDMA5 true
#define PWM132_EASYDMATEMP false
#define PWM132_IDLE_OUT true
#define PWM132_COMPARE_MATCH true
#define PWM132_FEATURES_V2 false
#define PWM132_NO_FEATURES_V2 true
#define PWM132_EASYDMALISTINCLUDED false
#define PWM132_EASYDMAMODEINCLUDED false
#define PWM132_EASYDMAFULLLPMODEINCLUDED false
#define PWM132_EASYDMAPATTERNMATCHERINCLUDED false
#define PWM132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED true
#define PWM132_EASYDMASTOPTASKINCLUDED true

#define PWM133_EASYDMA5 true
#define PWM133_EASYDMATEMP false
#define PWM133_IDLE_OUT true
#define PWM133_COMPARE_MATCH true
#define PWM133_FEATURES_V2 false
#define PWM133_NO_FEATURES_V2 true
#define PWM133_EASYDMALISTINCLUDED false
#define PWM133_EASYDMAMODEINCLUDED false
#define PWM133_EASYDMAFULLLPMODEINCLUDED false
#define PWM133_EASYDMAPATTERNMATCHERINCLUDED false
#define PWM133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED true
#define PWM133_EASYDMASTOPTASKINCLUDED true

/*SPI Slave*/
#define SPIS_PRESENT
#define SPIS_COUNT 9

#define SPIS120_LEGACYPSEL false
#define SPIS120_LEGACYEDMA false
#define SPIS120_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS120_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS120_EASYDMA5 true
#define SPIS120_EASYDMATEMP false
#define SPIS120_EASYDMALISTINCLUDED true
#define SPIS120_EASYDMAMODEINCLUDED false
#define SPIS120_EASYDMAFULLLPMODEINCLUDED false
#define SPIS120_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS120_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS120_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS120_EASYDMASTOPTASKINCLUDED true

#define SPIS130_LEGACYPSEL false
#define SPIS130_LEGACYEDMA false
#define SPIS130_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS130_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS130_EASYDMA5 true
#define SPIS130_EASYDMATEMP false
#define SPIS130_EASYDMALISTINCLUDED true
#define SPIS130_EASYDMAMODEINCLUDED false
#define SPIS130_EASYDMAFULLLPMODEINCLUDED false
#define SPIS130_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS130_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS130_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS130_EASYDMASTOPTASKINCLUDED true

#define SPIS131_LEGACYPSEL false
#define SPIS131_LEGACYEDMA false
#define SPIS131_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS131_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS131_EASYDMA5 true
#define SPIS131_EASYDMATEMP false
#define SPIS131_EASYDMALISTINCLUDED true
#define SPIS131_EASYDMAMODEINCLUDED false
#define SPIS131_EASYDMAFULLLPMODEINCLUDED false
#define SPIS131_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS131_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS131_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS131_EASYDMASTOPTASKINCLUDED true

#define SPIS132_LEGACYPSEL false
#define SPIS132_LEGACYEDMA false
#define SPIS132_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS132_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS132_EASYDMA5 true
#define SPIS132_EASYDMATEMP false
#define SPIS132_EASYDMALISTINCLUDED true
#define SPIS132_EASYDMAMODEINCLUDED false
#define SPIS132_EASYDMAFULLLPMODEINCLUDED false
#define SPIS132_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS132_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS132_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS132_EASYDMASTOPTASKINCLUDED true

#define SPIS133_LEGACYPSEL false
#define SPIS133_LEGACYEDMA false
#define SPIS133_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS133_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS133_EASYDMA5 true
#define SPIS133_EASYDMATEMP false
#define SPIS133_EASYDMALISTINCLUDED true
#define SPIS133_EASYDMAMODEINCLUDED false
#define SPIS133_EASYDMAFULLLPMODEINCLUDED false
#define SPIS133_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS133_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS133_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS133_EASYDMASTOPTASKINCLUDED true

#define SPIS134_LEGACYPSEL false
#define SPIS134_LEGACYEDMA false
#define SPIS134_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS134_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS134_EASYDMA5 true
#define SPIS134_EASYDMATEMP false
#define SPIS134_EASYDMALISTINCLUDED true
#define SPIS134_EASYDMAMODEINCLUDED false
#define SPIS134_EASYDMAFULLLPMODEINCLUDED false
#define SPIS134_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS134_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS134_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS134_EASYDMASTOPTASKINCLUDED true

#define SPIS135_LEGACYPSEL false
#define SPIS135_LEGACYEDMA false
#define SPIS135_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS135_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS135_EASYDMA5 true
#define SPIS135_EASYDMATEMP false
#define SPIS135_EASYDMALISTINCLUDED true
#define SPIS135_EASYDMAMODEINCLUDED false
#define SPIS135_EASYDMAFULLLPMODEINCLUDED false
#define SPIS135_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS135_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS135_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS135_EASYDMASTOPTASKINCLUDED true

#define SPIS136_LEGACYPSEL false
#define SPIS136_LEGACYEDMA false
#define SPIS136_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS136_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS136_EASYDMA5 true
#define SPIS136_EASYDMATEMP false
#define SPIS136_EASYDMALISTINCLUDED true
#define SPIS136_EASYDMAMODEINCLUDED false
#define SPIS136_EASYDMAFULLLPMODEINCLUDED false
#define SPIS136_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS136_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS136_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS136_EASYDMASTOPTASKINCLUDED true

#define SPIS137_LEGACYPSEL false
#define SPIS137_LEGACYEDMA false
#define SPIS137_EASYDMA_MAXCNT_SIZE_MIN 0
#define SPIS137_EASYDMA_MAXCNT_SIZE_MAX 15
#define SPIS137_EASYDMA5 true
#define SPIS137_EASYDMATEMP false
#define SPIS137_EASYDMALISTINCLUDED true
#define SPIS137_EASYDMAMODEINCLUDED false
#define SPIS137_EASYDMAFULLLPMODEINCLUDED false
#define SPIS137_EASYDMAPATTERNMATCHERINCLUDED true
#define SPIS137_EASYDMANUMMATCHCHANNELS_MIN 0
#define SPIS137_EASYDMANUMMATCHCHANNELS_MAX 3
#define SPIS137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SPIS137_EASYDMASTOPTASKINCLUDED true

/*UART with EasyDMA*/
#define UARTE_PRESENT
#define UARTE_COUNT 9

#define UARTE120_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE120_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE120_EASYDMA5 true
#define UARTE120_EASYDMATEMP false
#define UARTE120_TIMEOUT_INTERRUPT true
#define UARTE120_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE120_CORE_CLOCK_16 false
#define UARTE120_CORE_CLOCK_320 true
#define UARTE120_EASYDMALISTINCLUDED false
#define UARTE120_EASYDMAMODEINCLUDED false
#define UARTE120_EASYDMAFULLLPMODEINCLUDED false
#define UARTE120_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE120_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE120_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE120_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE120_EASYDMASTOPTASKINCLUDED true

#define UARTE130_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE130_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE130_EASYDMA5 true
#define UARTE130_EASYDMATEMP false
#define UARTE130_TIMEOUT_INTERRUPT true
#define UARTE130_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE130_CORE_CLOCK_16 true
#define UARTE130_CORE_CLOCK_320 false
#define UARTE130_EASYDMALISTINCLUDED false
#define UARTE130_EASYDMAMODEINCLUDED false
#define UARTE130_EASYDMAFULLLPMODEINCLUDED false
#define UARTE130_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE130_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE130_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE130_EASYDMASTOPTASKINCLUDED true

#define UARTE131_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE131_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE131_EASYDMA5 true
#define UARTE131_EASYDMATEMP false
#define UARTE131_TIMEOUT_INTERRUPT true
#define UARTE131_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE131_CORE_CLOCK_16 true
#define UARTE131_CORE_CLOCK_320 false
#define UARTE131_EASYDMALISTINCLUDED false
#define UARTE131_EASYDMAMODEINCLUDED false
#define UARTE131_EASYDMAFULLLPMODEINCLUDED false
#define UARTE131_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE131_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE131_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE131_EASYDMASTOPTASKINCLUDED true

#define UARTE132_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE132_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE132_EASYDMA5 true
#define UARTE132_EASYDMATEMP false
#define UARTE132_TIMEOUT_INTERRUPT true
#define UARTE132_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE132_CORE_CLOCK_16 true
#define UARTE132_CORE_CLOCK_320 false
#define UARTE132_EASYDMALISTINCLUDED false
#define UARTE132_EASYDMAMODEINCLUDED false
#define UARTE132_EASYDMAFULLLPMODEINCLUDED false
#define UARTE132_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE132_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE132_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE132_EASYDMASTOPTASKINCLUDED true

#define UARTE133_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE133_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE133_EASYDMA5 true
#define UARTE133_EASYDMATEMP false
#define UARTE133_TIMEOUT_INTERRUPT true
#define UARTE133_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE133_CORE_CLOCK_16 true
#define UARTE133_CORE_CLOCK_320 false
#define UARTE133_EASYDMALISTINCLUDED false
#define UARTE133_EASYDMAMODEINCLUDED false
#define UARTE133_EASYDMAFULLLPMODEINCLUDED false
#define UARTE133_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE133_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE133_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE133_EASYDMASTOPTASKINCLUDED true

#define UARTE134_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE134_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE134_EASYDMA5 true
#define UARTE134_EASYDMATEMP false
#define UARTE134_TIMEOUT_INTERRUPT true
#define UARTE134_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE134_CORE_CLOCK_16 true
#define UARTE134_CORE_CLOCK_320 false
#define UARTE134_EASYDMALISTINCLUDED false
#define UARTE134_EASYDMAMODEINCLUDED false
#define UARTE134_EASYDMAFULLLPMODEINCLUDED false
#define UARTE134_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE134_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE134_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE134_EASYDMASTOPTASKINCLUDED true

#define UARTE135_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE135_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE135_EASYDMA5 true
#define UARTE135_EASYDMATEMP false
#define UARTE135_TIMEOUT_INTERRUPT true
#define UARTE135_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE135_CORE_CLOCK_16 true
#define UARTE135_CORE_CLOCK_320 false
#define UARTE135_EASYDMALISTINCLUDED false
#define UARTE135_EASYDMAMODEINCLUDED false
#define UARTE135_EASYDMAFULLLPMODEINCLUDED false
#define UARTE135_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE135_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE135_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE135_EASYDMASTOPTASKINCLUDED true

#define UARTE136_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE136_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE136_EASYDMA5 true
#define UARTE136_EASYDMATEMP false
#define UARTE136_TIMEOUT_INTERRUPT true
#define UARTE136_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE136_CORE_CLOCK_16 true
#define UARTE136_CORE_CLOCK_320 false
#define UARTE136_EASYDMALISTINCLUDED false
#define UARTE136_EASYDMAMODEINCLUDED false
#define UARTE136_EASYDMAFULLLPMODEINCLUDED false
#define UARTE136_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE136_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE136_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE136_EASYDMASTOPTASKINCLUDED true

#define UARTE137_EASYDMA_MAXCNT_SIZE_MIN 0
#define UARTE137_EASYDMA_MAXCNT_SIZE_MAX 7
#define UARTE137_EASYDMA5 true
#define UARTE137_EASYDMATEMP false
#define UARTE137_TIMEOUT_INTERRUPT true
#define UARTE137_CONFIGURABLE_DATA_FRAME_SIZE true
#define UARTE137_CORE_CLOCK_16 true
#define UARTE137_CORE_CLOCK_320 false
#define UARTE137_EASYDMALISTINCLUDED false
#define UARTE137_EASYDMAMODEINCLUDED false
#define UARTE137_EASYDMAFULLLPMODEINCLUDED false
#define UARTE137_EASYDMAPATTERNMATCHERINCLUDED true
#define UARTE137_EASYDMANUMMATCHCHANNELS_MIN 0
#define UARTE137_EASYDMANUMMATCHCHANNELS_MAX 3
#define UARTE137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define UARTE137_EASYDMASTOPTASKINCLUDED true

/*Coexistence controller*/
#define COEXC_PRESENT
#define COEXC_COUNT 1

#define COEXC_NCLIENTS_MIN 0
#define COEXC_NCLIENTS_MAX 5
#define COEXC_NMODES_MIN 0
#define COEXC_NMODES_MAX 3
#define COEXC_NCCMALLOWMODES_MIN 0
#define COEXC_NCCMALLOWMODES_MAX 3
#define COEXC_NPRIORITYBITS_MIN 16
#define COEXC_NPRIORITYBITS_MAX 23

/*Antenna switch controller*/
#define ANTSWC_PRESENT
#define ANTSWC_COUNT 1

#define ANTSWC_NRADIOS 2
#define ANTSWC_NANTSWBITS 1

/*Real-time counter*/
#define RTC_PRESENT
#define RTC_COUNT 2

#define RTC130_CC_NUM_MIN 0
#define RTC130_CC_NUM_MAX 3

#define RTC131_CC_NUM_MIN 0
#define RTC131_CC_NUM_MAX 3

/*Watchdog Timer*/
#define WDT_PRESENT
#define WDT_COUNT 2

#define WDT131_START_ON_RESET false
#define WDT131_CRV_RESETVALUE 4294967295
#define WDT131_ALLOW_STOP false

#define WDT132_START_ON_RESET false
#define WDT132_CRV_RESETVALUE 4294967295
#define WDT132_ALLOW_STOP false

/*Event generator unit*/
#define EGU_PRESENT
#define EGU_COUNT 1

#define EGU130_PEND false
#define EGU130_CH_NUM_MIN 0
#define EGU130_CH_NUM_MAX 7

/*GPIO Port*/
#define GPIO_PRESENT
#define GPIO_COUNT 8

#define P0_PIN_NUM_MIN 0
#define P0_PIN_NUM_MAX 11
#define P0_PINS_PRESENT 0xfffffffful
#define P0_DRIVECTRL false
#define P0_PWRCTRL false
#define P0_PWRCTRL_SEPARATE_REG true
#define P0_VSS_FLOAT_DFT true
#define P0_PIN_OWNER_SEC true
#define P0_WIFI_CORE_PRESENT true

#define P1_PIN_NUM_MIN 0
#define P1_PIN_NUM_MAX 11
#define P1_PINS_PRESENT 0xfffffffful
#define P1_DRIVECTRL false
#define P1_PWRCTRL false
#define P1_PWRCTRL_SEPARATE_REG true
#define P1_VSS_FLOAT_DFT true
#define P1_PIN_OWNER_SEC true
#define P1_WIFI_CORE_PRESENT true

#define P2_PIN_NUM_MIN 0
#define P2_PIN_NUM_MAX 17
#define P2_PINS_PRESENT 0xfffffffful
#define P2_DRIVECTRL false
#define P2_PWRCTRL false
#define P2_PWRCTRL_SEPARATE_REG true
#define P2_VSS_FLOAT_DFT true
#define P2_PIN_OWNER_SEC true
#define P2_WIFI_CORE_PRESENT true

#define P3_PIN_NUM_MIN 0
#define P3_PIN_NUM_MAX 17
#define P3_PINS_PRESENT 0xfffffffful
#define P3_DRIVECTRL false
#define P3_PWRCTRL false
#define P3_PWRCTRL_SEPARATE_REG true
#define P3_VSS_FLOAT_DFT true
#define P3_PIN_OWNER_SEC true
#define P3_WIFI_CORE_PRESENT true

#define P5_PIN_NUM_MIN 0
#define P5_PIN_NUM_MAX 13
#define P5_PINS_PRESENT 0xfffffffful
#define P5_DRIVECTRL false
#define P5_PWRCTRL false
#define P5_PWRCTRL_SEPARATE_REG true
#define P5_VSS_FLOAT_DFT true
#define P5_PIN_OWNER_SEC true
#define P5_WIFI_CORE_PRESENT true

#define P6_PIN_NUM_MIN 0
#define P6_PIN_NUM_MAX 13
#define P6_PINS_PRESENT 0xfffffffful
#define P6_DRIVECTRL true
#define P6_PWRCTRL false
#define P6_PWRCTRL_SEPARATE_REG true
#define P6_VSS_FLOAT_DFT true
#define P6_PIN_OWNER_SEC true
#define P6_WIFI_CORE_PRESENT true

#define P8_PIN_NUM_MIN 0
#define P8_PIN_NUM_MAX 4
#define P8_PINS_PRESENT 0xfffffffful
#define P8_DRIVECTRL true
#define P8_PWRCTRL false
#define P8_PWRCTRL_SEPARATE_REG true
#define P8_VSS_FLOAT_DFT true
#define P8_PIN_OWNER_SEC true
#define P8_WIFI_CORE_PRESENT true

#define P9_PIN_NUM_MIN 0
#define P9_PIN_NUM_MAX 5
#define P9_PINS_PRESENT 0xfffffffful
#define P9_DRIVECTRL false
#define P9_PWRCTRL true
#define P9_PWRCTRL_SEPARATE_REG true
#define P9_VSS_FLOAT_DFT true
#define P9_PIN_OWNER_SEC true
#define P9_WIFI_CORE_PRESENT true

/*GPIO Internal*/
#define GPIOINTERNAL_PRESENT
#define GPIOINTERNAL_COUNT 1

/*Reset hub*/
#define RESETHUB_PRESENT
#define RESETHUB_COUNT 1

/*Analog to Digital Converter*/
#define SAADC_PRESENT
#define SAADC_COUNT 1

#define SAADC_EASYDMA5 false
#define SAADC_EASYDMATEMP true
#define SAADC_PSEL_V2 true
#define SAADC_TASKS_CALIBRATEGAIN true
#define SAADC_EASYDMALISTINCLUDED false
#define SAADC_EASYDMAMODEINCLUDED false
#define SAADC_EASYDMAFULLLPMODEINCLUDED false
#define SAADC_EASYDMAPATTERNMATCHERINCLUDED false
#define SAADC_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define SAADC_EASYDMASTOPTASKINCLUDED true

/*Comparator*/
#define COMP_PRESENT
#define COMP_COUNT 1

/*Low-power comparator*/
#define LPCOMP_PRESENT
#define LPCOMP_COUNT 1

/*Temperature Sensor*/
#define TEMP_PRESENT
#define TEMP_COUNT 1

/*NFC-A compatible radio NFC-A compatible radio*/
#define NFCT_PRESENT
#define NFCT_COUNT 1

#define NFCT_EASYDMA5 false
#define NFCT_EASYDMATEMP false

/*Time division multiplexed audio interface*/
#define TDM_PRESENT
#define TDM_COUNT 3

#define TDM130_EASYDMA5 true
#define TDM130_EASYDMATEMP false
#define TDM130_EASYDMALISTINCLUDED false
#define TDM130_EASYDMAMODEINCLUDED true
#define TDM130_EASYDMAFULLLPMODEINCLUDED false

#define TDM131_EASYDMA5 true
#define TDM131_EASYDMATEMP false
#define TDM131_EASYDMALISTINCLUDED false
#define TDM131_EASYDMAMODEINCLUDED true
#define TDM131_EASYDMAFULLLPMODEINCLUDED false

#define TDM132_EASYDMA5 true
#define TDM132_EASYDMATEMP false
#define TDM132_EASYDMALISTINCLUDED false
#define TDM132_EASYDMAMODEINCLUDED true
#define TDM132_EASYDMAFULLLPMODEINCLUDED false

/*Quadrature Decoder*/
#define QDEC_PRESENT
#define QDEC_COUNT 2

#define QDEC130_LEGACYPSEL false

#define QDEC131_LEGACYPSEL false

/*SIM card interface*/
#define SIMIF_PRESENT
#define SIMIF_COUNT 1

/*I2C compatible Two-Wire Master Interface with EasyDMA*/
#define TWIM_PRESENT
#define TWIM_COUNT 8

#define TWIM130_EASYDMA5 true
#define TWIM130_EASYDMATEMP false
#define TWIM130_EASYDMALISTINCLUDED true
#define TWIM130_EASYDMAMODEINCLUDED false
#define TWIM130_EASYDMAFULLLPMODEINCLUDED false
#define TWIM130_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM130_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM130_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM130_EASYDMASTOPTASKINCLUDED true

#define TWIM131_EASYDMA5 true
#define TWIM131_EASYDMATEMP false
#define TWIM131_EASYDMALISTINCLUDED true
#define TWIM131_EASYDMAMODEINCLUDED false
#define TWIM131_EASYDMAFULLLPMODEINCLUDED false
#define TWIM131_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM131_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM131_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM131_EASYDMASTOPTASKINCLUDED true

#define TWIM132_EASYDMA5 true
#define TWIM132_EASYDMATEMP false
#define TWIM132_EASYDMALISTINCLUDED true
#define TWIM132_EASYDMAMODEINCLUDED false
#define TWIM132_EASYDMAFULLLPMODEINCLUDED false
#define TWIM132_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM132_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM132_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM132_EASYDMASTOPTASKINCLUDED true

#define TWIM133_EASYDMA5 true
#define TWIM133_EASYDMATEMP false
#define TWIM133_EASYDMALISTINCLUDED true
#define TWIM133_EASYDMAMODEINCLUDED false
#define TWIM133_EASYDMAFULLLPMODEINCLUDED false
#define TWIM133_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM133_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM133_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM133_EASYDMASTOPTASKINCLUDED true

#define TWIM134_EASYDMA5 true
#define TWIM134_EASYDMATEMP false
#define TWIM134_EASYDMALISTINCLUDED true
#define TWIM134_EASYDMAMODEINCLUDED false
#define TWIM134_EASYDMAFULLLPMODEINCLUDED false
#define TWIM134_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM134_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM134_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM134_EASYDMASTOPTASKINCLUDED true

#define TWIM135_EASYDMA5 true
#define TWIM135_EASYDMATEMP false
#define TWIM135_EASYDMALISTINCLUDED true
#define TWIM135_EASYDMAMODEINCLUDED false
#define TWIM135_EASYDMAFULLLPMODEINCLUDED false
#define TWIM135_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM135_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM135_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM135_EASYDMASTOPTASKINCLUDED true

#define TWIM136_EASYDMA5 true
#define TWIM136_EASYDMATEMP false
#define TWIM136_EASYDMALISTINCLUDED true
#define TWIM136_EASYDMAMODEINCLUDED false
#define TWIM136_EASYDMAFULLLPMODEINCLUDED false
#define TWIM136_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM136_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM136_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM136_EASYDMASTOPTASKINCLUDED true

#define TWIM137_EASYDMA5 true
#define TWIM137_EASYDMATEMP false
#define TWIM137_EASYDMALISTINCLUDED true
#define TWIM137_EASYDMAMODEINCLUDED false
#define TWIM137_EASYDMAFULLLPMODEINCLUDED false
#define TWIM137_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIM137_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIM137_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIM137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIM137_EASYDMASTOPTASKINCLUDED true

/*I2C compatible Two-Wire Slave Interface with EasyDMA*/
#define TWIS_PRESENT
#define TWIS_COUNT 8

#define TWIS130_EASYDMA5 true
#define TWIS130_EASYDMATEMP false
#define TWIS130_EASYDMALISTINCLUDED true
#define TWIS130_EASYDMAMODEINCLUDED false
#define TWIS130_EASYDMAFULLLPMODEINCLUDED false
#define TWIS130_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS130_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS130_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS130_EASYDMASTOPTASKINCLUDED true

#define TWIS131_EASYDMA5 true
#define TWIS131_EASYDMATEMP false
#define TWIS131_EASYDMALISTINCLUDED true
#define TWIS131_EASYDMAMODEINCLUDED false
#define TWIS131_EASYDMAFULLLPMODEINCLUDED false
#define TWIS131_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS131_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS131_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS131_EASYDMASTOPTASKINCLUDED true

#define TWIS132_EASYDMA5 true
#define TWIS132_EASYDMATEMP false
#define TWIS132_EASYDMALISTINCLUDED true
#define TWIS132_EASYDMAMODEINCLUDED false
#define TWIS132_EASYDMAFULLLPMODEINCLUDED false
#define TWIS132_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS132_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS132_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS132_EASYDMASTOPTASKINCLUDED true

#define TWIS133_EASYDMA5 true
#define TWIS133_EASYDMATEMP false
#define TWIS133_EASYDMALISTINCLUDED true
#define TWIS133_EASYDMAMODEINCLUDED false
#define TWIS133_EASYDMAFULLLPMODEINCLUDED false
#define TWIS133_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS133_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS133_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS133_EASYDMASTOPTASKINCLUDED true

#define TWIS134_EASYDMA5 true
#define TWIS134_EASYDMATEMP false
#define TWIS134_EASYDMALISTINCLUDED true
#define TWIS134_EASYDMAMODEINCLUDED false
#define TWIS134_EASYDMAFULLLPMODEINCLUDED false
#define TWIS134_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS134_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS134_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS134_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS134_EASYDMASTOPTASKINCLUDED true

#define TWIS135_EASYDMA5 true
#define TWIS135_EASYDMATEMP false
#define TWIS135_EASYDMALISTINCLUDED true
#define TWIS135_EASYDMAMODEINCLUDED false
#define TWIS135_EASYDMAFULLLPMODEINCLUDED false
#define TWIS135_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS135_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS135_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS135_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS135_EASYDMASTOPTASKINCLUDED true

#define TWIS136_EASYDMA5 true
#define TWIS136_EASYDMATEMP false
#define TWIS136_EASYDMALISTINCLUDED true
#define TWIS136_EASYDMAMODEINCLUDED false
#define TWIS136_EASYDMAFULLLPMODEINCLUDED false
#define TWIS136_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS136_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS136_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS136_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS136_EASYDMASTOPTASKINCLUDED true

#define TWIS137_EASYDMA5 true
#define TWIS137_EASYDMATEMP false
#define TWIS137_EASYDMALISTINCLUDED true
#define TWIS137_EASYDMAMODEINCLUDED false
#define TWIS137_EASYDMAFULLLPMODEINCLUDED false
#define TWIS137_EASYDMAPATTERNMATCHERINCLUDED true
#define TWIS137_EASYDMANUMMATCHCHANNELS_MIN 0
#define TWIS137_EASYDMANUMMATCHCHANNELS_MAX 3
#define TWIS137_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define TWIS137_EASYDMASTOPTASKINCLUDED true

/*Pulse Density Modulation (Digital Microphone) Interface*/
#define PDM_PRESENT
#define PDM_COUNT 4

#define PDM130_EASYDMA5 false
#define PDM130_EASYDMATEMP true
#define PDM130_SAMPLE16 false
#define PDM130_SAMPLE48 true
#define PDM130_EASYDMALISTINCLUDED false
#define PDM130_EASYDMAMODEINCLUDED false
#define PDM130_EASYDMAFULLLPMODEINCLUDED false
#define PDM130_EASYDMAPATTERNMATCHERINCLUDED false
#define PDM130_EASYDMAMATCHEVENTRANGE_MIN 0
#define PDM130_EASYDMAMATCHEVENTRANGE_MAX 3
#define PDM130_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define PDM130_EASYDMASTOPTASKINCLUDED true

#define PDM131_EASYDMA5 false
#define PDM131_EASYDMATEMP true
#define PDM131_SAMPLE16 false
#define PDM131_SAMPLE48 true
#define PDM131_EASYDMALISTINCLUDED false
#define PDM131_EASYDMAMODEINCLUDED false
#define PDM131_EASYDMAFULLLPMODEINCLUDED false
#define PDM131_EASYDMAPATTERNMATCHERINCLUDED false
#define PDM131_EASYDMAMATCHEVENTRANGE_MIN 0
#define PDM131_EASYDMAMATCHEVENTRANGE_MAX 3
#define PDM131_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define PDM131_EASYDMASTOPTASKINCLUDED true

#define PDM132_EASYDMA5 false
#define PDM132_EASYDMATEMP true
#define PDM132_SAMPLE16 false
#define PDM132_SAMPLE48 true
#define PDM132_EASYDMALISTINCLUDED false
#define PDM132_EASYDMAMODEINCLUDED false
#define PDM132_EASYDMAFULLLPMODEINCLUDED false
#define PDM132_EASYDMAPATTERNMATCHERINCLUDED false
#define PDM132_EASYDMAMATCHEVENTRANGE_MIN 0
#define PDM132_EASYDMAMATCHEVENTRANGE_MAX 3
#define PDM132_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define PDM132_EASYDMASTOPTASKINCLUDED true

#define PDM133_EASYDMA5 false
#define PDM133_EASYDMATEMP true
#define PDM133_SAMPLE16 false
#define PDM133_SAMPLE48 true
#define PDM133_EASYDMALISTINCLUDED false
#define PDM133_EASYDMAMODEINCLUDED false
#define PDM133_EASYDMAFULLLPMODEINCLUDED false
#define PDM133_EASYDMAPATTERNMATCHERINCLUDED false
#define PDM133_EASYDMAMATCHEVENTRANGE_MIN 0
#define PDM133_EASYDMAMATCHEVENTRANGE_MAX 3
#define PDM133_EASYDMA_CURRENT_AMOUNT_REGISTER_INCLUDED false
#define PDM133_EASYDMASTOPTASKINCLUDED true


#ifdef __cplusplus
}
#endif
#endif /* NRF7140_BBPR_PERIPHERALS_H */

