AS = riscv64-elf-as
CC = riscv64-elf-gcc
LD = riscv64-elf-ld
OBJCOPY = riscv64-elf-objcopy
OBJDUMP = riscv64-elf-objdump
SIZE = riscv64-elf-size

LDSCRIPT = arch/riscv/link.lds

export AS CC LD OBJCOPY OBJDUMP SIZE LDSCRIPT
